require 'tty-prompt'
require 'paint'
require "net/http"
require "uri"
require "colorize"
require "yaml"
require "json"
require "redis"
require "netrc"
require "optparse"
require "tty-spinner"

require File.dirname(__FILE__) + "/Api/get"
require File.dirname(__FILE__) + "/Api/post"
require File.dirname(__FILE__) + "/Api/patch"
require File.dirname(__FILE__) + "/Api/refresh_token"
require File.dirname(__FILE__) + "/Authentication/login"
require File.dirname(__FILE__) + "/Authentication/secret_file"
require File.dirname(__FILE__) + "/Authentication/create_user"
require File.dirname(__FILE__) + "/init/init_application"
require File.dirname(__FILE__) + "/init/init_organization"
require File.dirname(__FILE__) + "/init/init_project"
require File.dirname(__FILE__) + "/init/init_ssh"
require File.dirname(__FILE__) + "/replica/init"
require File.dirname(__FILE__) + "/replica/log"
require File.dirname(__FILE__) + "/replica/command"
require File.dirname(__FILE__) + "/replica/scale"
require File.dirname(__FILE__) + "/db/init"
require File.dirname(__FILE__) + "/db/create"
require File.dirname(__FILE__) + "/db/servers"
require File.dirname(__FILE__) + "/db/login"
require File.dirname(__FILE__) + "/help"
require File.dirname(__FILE__) + "/auth"
